<div id='left-box'>
	<?php
		echo("<h2 class='h2-left-box'>HTML5 Introduction</h2>");
		echo("<a href='".HTML_INTRODUCTION_PHP."' class='left-box-link'>HTML Introduction</a>");
		echo("<a href='".HTML_BASICS_PHP."' class='left-box-link'>Basics</a>");
		echo("<a href='".HTML_HTML_TAGS_PHP."' class='left-box-link'>Html Tags</a>");
		echo("<a href='".HTML_ATTRIBUTE_PHP."' class='left-box-link'>Attributes</a>");
		echo("<a href='#' class='left-box-link'>Point 5</a>");
		echo("<a href='#' class='left-box-link'>Point 6</a>");
		echo("<a href='#' class='left-box-link'>Point 7</a>");
		echo("<h2 class='h2-left-box'>Balise HTML</h2>");
		echo("<a href='".HTML_COMMENT_TAG_PHP."' class='left-box-link'><code>&lt!-- --&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lt!DOCTYPE&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lta&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltabbr&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltaddress&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltarea&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltarticle&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltaside&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltaudio&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltb&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltbase&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltbdi&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltbdo&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltblockquote&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltbody&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltbr&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltbutton&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltcanvas&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltcaption&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltcite&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltcode&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltcol&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltcolgroup&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdata&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdatalist&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdd&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdel&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdetails&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdfn&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdialog&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdiv&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdl&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltdt&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltem&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltembed&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltfieldset&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltfigcaption&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltfigure&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltfooter&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltform&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lth1&gt</code> to <code>&lth6&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lthead&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltheader&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lthr&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lthtml&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lti&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltiframe&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltimg&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltinput&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltins&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltkdb&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltlabel&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltlegend&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltli&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltlink&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltmain&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltmap&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltmark&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltmeta&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltmeter&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltnav&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltnoscript&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltobject&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltol&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltoptgroup&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltoption&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltoutput&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltp&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltparam&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltpicture&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltpre&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltprogress&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltq&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltrp&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltrt&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltruby&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lts&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsamp&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltscript&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsection&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltselect&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsmall&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsource&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltspan&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltstrong&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltstyle&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsub&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsummary&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsup&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltsvg&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttable&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttbody&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttd&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttemplate&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttextarea&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttfoot&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltth&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltthead&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttime&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttitle&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttr&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&lttrack&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltu&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltul&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltvar&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltvideo&gt</code></a>");
		echo("<a href='#' class='left-box-link'><code>&ltwbr&gt</code></a>");

		echo("<h2 class='h2-left-box'>HTML5 Tutorial</h2>");
		echo("<a href='#' class='left-box-link'>Point 1</a>");
		echo("<a href='#' class='left-box-link'>Point 2</a>");
		echo("<a href='#' class='left-box-link'>Point 3</a>");
		echo("<a href='#' class='left-box-link'>Point 4</a>");
		echo("<a href='#' class='left-box-link'>Point 5</a>");
		echo("<a href='#' class='left-box-link'>Point 6</a>");
		echo("<a href='#' class='left-box-link'>Point 7</a>");
		echo("<h2 class='h2-left-box'>HTML5 DOM</h2>");
		echo("<a href='#' class='left-box-link'>Point 1</a>");
		echo("<a href='#' class='left-box-link'>Point 2</a>");
		echo("<a href='#' class='left-box-link'>Point 3</a>");
		echo("<a href='#' class='left-box-link'>Point 4</a>");
		echo("<a href='#' class='left-box-link'>Point 5</a>");
		echo("<a href='#' class='left-box-link'>Point 6</a>");
		echo("<a href='#' class='left-box-link'>Point 7</a>");
		echo("<h2 class='h2-left-box'>HTML5 Tutorial</h2>");
		echo("<a href='#' class='left-box-link'>Point 1</a>");
		echo("<a href='#' class='left-box-link'>Point 2</a>");
		echo("<a href='#' class='left-box-link'>Point 3</a>");
		echo("<a href='#' class='left-box-link'>Point 4</a>");
		echo("<a href='#' class='left-box-link'>Point 5</a>");
		echo("<a href='#' class='left-box-link'>Point 6</a>");
		echo("<a href='#' class='left-box-link'>Point 7</a>");
		echo("<h2 class='h2-left-box'>HTML5 DOM</h2>");
		echo("<a href='#' class='left-box-link'>Point 1</a>");
		echo("<a href='#' class='left-box-link'>Point 2</a>");
		echo("<a href='#' class='left-box-link'>Point 3</a>");
		echo("<a href='#' class='left-box-link'>Point 4</a>");
		echo("<a href='#' class='left-box-link'>Point 5</a>");
		echo("<a href='#' class='left-box-link'>Point 6</a>");
		echo("<a href='#' class='left-box-link'>Point 7</a>");
	?>
</div>